name: Deploy Azure Policy

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  
jobs:
  terraform:
    name: Deploy
    runs-on: windows-latest
    environment: Sythronic-Demo
    env:
      working-directory: ./terraform
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      
    steps:

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

          # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.working-directory }}

    # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

    # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: ${{ env.working-directory }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.working-directory }}
